apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service-deployment
  labels:
    app: subscription-service-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      tier: subscription-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: subscription-service
    spec:
      containers:
        - name: subscription-service
          image: koalaa13/subscription-service
          imagePullPolicy: "Always"
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgres-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: subscription-service-config-map
                  key: dbUrl
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: subscription-service-config-map
                  key: dbUser
            - name: SPRING_SERVER_PORT
              value: '{{ .Values.port }}'
          ports:
            - name: web
              containerPort: {{ .Values.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3