apiVersion: v1
kind: Service
metadata:
  name: subscription-service
  labels:
    app: subscription-service
spec:
  selector:
    tier: subscription-service
  ports:
    - protocol: TCP
      name: subscription-service-metrics
      port: 80
      targetPort: {{ .Values.port }}
  type: ClusterIP