port: 8080
replicaCount: 1

postgresql:
  primary:
    persistence:
      size: 1Gi
  auth:
    database: app
    postgresPassword: changeme

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: { }

prometheus-postgres-exporter:
  serviceMonitor:
    enabled: true
  config:
    datasource:
      host: auth-service-postgresql
      database: app
      user: postgres
      password: changeme