apiVersion: v1
kind: Service
metadata:
  name: file-service
  labels:
    app: file-service
spec:
  selector:
    tier: file-service
  ports:
    - protocol: TCP
      name: file-service-metrics
      port: 80
      targetPort: {{ .Values.port }}
  type: ClusterIP