apiVersion: v1
kind: Service
metadata:
  name: bank-service
  labels:
    app: bank-service
spec:
  selector:
    tier: bank-service
  ports:
    - protocol: TCP
      name: bank-service-metrics
      port: 80
      targetPort: {{ .Values.port }}
  type: ClusterIP