metrics:
  jmx:
    enabled: true
  serviceMonitor:
    enabled: true
controller:
  persistence:
    size: 1Gi
  replicaCount: 3
listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT