auth:
  jwt:
    secret: 7f9fb1eb85763d9919dea2d3092bfff2229d87cca78f62bb9aaf35328880d410

server:
  port: ${SPRING_SERVER_PORT}

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: subscription
          uri: http://subscription-service
          predicates:
            - Path=/subscription/**
          filters:
            - RewritePath=/subscription/?(?<segment>.*), /api/v1/$\{segment}
            - AuthorizationFilter
        - id: bookstore
          uri: http://book-service
          predicates:
            - Path=/books/**
          filters:
            - RewritePath=/books/?(?<segment>.*), /api/v1/$\{segment}
            - AuthorizationFilter
        - id: moderatorRequests
          uri: http://moderation-service
          predicates:
            - Path=/moderator/**
          filters:
            - RewritePath=/moderator/?(?<segment>.*), /api/v1/$\{segment}
            - AuthorizationFilter
        - id: fileGet
          uri: http://file-service
          predicates:
            - Path=/files/**
          filters:
            - RewritePath=/files/?(?<segment>.*), /api/v1/$\{segment}
            - AuthorizationFilter
        - id: registration
          uri: http://auth-service
          predicates:
            - Path=/registration
          filters:
            - RewritePath=/registration, /auth/user
        - id: moderatorRegistration
          uri: http://moderation-service
          predicates:
            - Path=/registration/moderator
          filters:
            - RewritePath=/registration/moderator, /auth/moderator
            - AuthorizationFilter
        - id: adminRegistration
          uri: http://auth-service
          predicates:
            - Path=/registration/admin
          filters:
            - RewritePath=/registration/admin, /auth/admin
            - AuthorizationFilter
        - id: token
          uri: http://auth-service
          predicates:
            - Path=/login
          filters:
            - RewritePath=/login, /auth/token