auth:
  jwt:
    secret: 7f9fb1eb85763d9919dea2d3092bfff2229d87cca78f62bb9aaf35328880d410

server:
  port: 8091

spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: bookstore
          uri: http://localhost:8090
          predicates:
            - Path=/books/**
          filters:
            - RewritePath=/books/?(?<segment>.*), /api/v1/$\{segment}
            - AuthorizationFilter
        - id: moderatorAssignRequest
          uri: http://localhost:8092
          predicates:
            - Path=/moderator/assign
          filters:
            - RewritePath=/moderator/assign, /api/v1/assign
            - AuthorizationFilter
        - id: fileModerationGet
          uri: http://localhost:8082
          predicates:
            - Path=/files/**
          filters:
            - RewritePath=/files/?(?<segment>.*), /api/v1/$\{segment}
            - AuthorizationFilter
        - id: registration
          uri: http://localhost:8080
          predicates:
            - Path=/registration
          filters:
            - RewritePath=/registration, /auth/user
        - id: moderatorRegistration
          uri: http://localhost:8080
          predicates:
            - Path=/registration/moderator
          filters:
            - RewritePath=/registration/moderator, /auth/moderator
        - id: adminRegistration
          uri: http://localhost:8080
          predicates:
            - Path=/registration/admin
          filters:
            - RewritePath=/registration/admin, /auth/admin
        - id: token
          uri: http://localhost:8080
          predicates:
            - Path=/login
          filters:
            - RewritePath=/login, /auth/token