{
 "title": "Auth service dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "uri", "label": "uri", "query": "health, auth/token, auth/user" },
   { "name": "method", "label": "http method", "query": "GET, POST, PUT, DELETE, PATCH" }
  ]
 },
 "panels": [
  {
   "title": "api methods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(irate(http_server_requests_seconds_count{container=\"auth-service\", method=\"$method\", uri=~\"/$uri\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "q50",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{container=\"auth-service\", method=\"$method\", uri=~\"/$uri\"}[1m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "q95",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{container=\"auth-service\", method=\"$method\", uri=~\"/$uri\"}[1m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "q99",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{container=\"auth-service\", method=\"$method\", uri=~\"/$uri\"}[1m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "500 response status rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{container=\"auth-service\", status=~\"5..\", method=\"$method\", uri=~\"/$uri\"}[1m]) / rate(http_server_requests_seconds_count{container=\"auth-service\", method=\"$method\", uri=~\"/$uri\"}[1m])) / count(count by (pod) (http_server_requests_seconds_count{container=\"auth-service\"})) or sum(http_server_requests_seconds_count{container=\"auth-service\"}) * 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "app resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "App podes cpu usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"auth-service-deployment-.*\"}[5m]))without(cpu, service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "App podes memory usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "avg(rate(container_memory_working_set_bytes{pod=~\"auth-service-deployment-.*\"}[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}