{
 "title": "Gateway(ingress) dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(irate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "q50",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "q95",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "q99",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "500 response status rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"5..\"}[1m]) / rate(nginx_ingress_controller_request_duration_seconds_count[1m])) / count(count by (pod) (nginx_ingress_controller_request_duration_seconds_count)) or sum(nginx_ingress_controller_request_duration_seconds_count) * 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "app resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "App podes cpu usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"gateway-deployment-.*\"}[5m]))without(cpu, service)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "App podes memory usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "avg(rate(container_memory_working_set_bytes{pod=~\"gateway-deployment-.*\"}[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}