apiVersion: v1
kind: Service
metadata:
  name: book-service
  labels:
    app: book-service
spec:
  selector:
    tier: book-service
  ports:
    - protocol: TCP
      name: book-service-metrics
      port: 80
      targetPort: {{ .Values.port }}
  type: ClusterIP