port: 8080
replicaCount: 1

postgresql:
  primary:
    persistence:
      size: 1Gi
  auth:
    database: app
    postgresPassword: changeme

prometheus-postgres-exporter:
  serviceMonitor:
    enabled: true
  config:
    datasource:
      host: book-service-postgresql
      database: app
      user: postgres
      password: changeme