apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    tier: gateway
  ports:
    - protocol: TCP
      name: gateway-metrics
      port: 80
      targetPort: {{ .Values.port }}
  type: ClusterIP